#include QMK_KEYBOARD_H
#include "action_layer.h"
/* #include "paradeon.h" */

enum {
    _BL = 0,
    _LL,
    _RL,
    _NL,
    _NSL,
    _NAL,
    _NCL,
    _NCL2,
    _XL,
    _VL,
    _GL,
    _ML,
    _FL,
    /* _SL, */
    /* _CL, */
};

/* enum { */
/*   TD_Z_ML = 0, */
/* }; */

/* qk_tap_dance_action_t tap_dance_actions[] = { */
/*   [TD_Z_ML] = ACTION_TAP_DANCE_DOUBLE(KC_Z, _ML), */
/* }; */

/* enum custom_keycodes { */
/*   DOUBLE_CLICK_MACRO = SAFE_RANGE */
/* }; */


/* bool process_record_user(uint16_t keycode, keyrecord_t *record) { */
/*   if (record->event.pressed) { */
/*     switch (keycode) { */
/*     case DOUBLE_CLICK_MACRO: SEND_STRING(SS_TAP(X_MS_BTN1)); return false; */
/*     } */
/*   } */
/*   return true; */
/* }; */

#define M_DOUBLE_CLICK M(0)
#define M_SPACE_EQL_SPACE M(1)
#define M_SPACE_EQL_GT_SPACE M(2)
#define M_SPACE_LT_EQL_SPACE M(3)
#define M_SPACE_MIN_GT_SPACE M(4)
#define M_SPACE_EQL_EQL_SPACE M(5)
#define M_SPACE_LT_SPACE M(6)
#define M_SPACE_GT_SPACE M(7)
#define M_SPACE_PLUS_SPACE M(8)
#define M_COL_SPACE QUES(9)
#define M_TRIPLE_CLICK M(10)
#define M_SHIFT_CLICK M(11)
#define M_CTRL_CLICK M(12)
#define M_SWITCH_WIN_START M(13)
#define M_SWITCH_MAC_START M(14)
#define M_SWITCH_WIN_P_START M(15)

const macro_t *action_get_macro(keyrecord_t *record, uint8_t id, uint8_t opt) {
  if (record->event.pressed) {
    switch (id) {
    case 0: return MACRO(T(BTN1), W(100), T(BTN1), END);
    case 1: return MACRO(T(SPC), T(EQL), T(SPC), END);
    case 2: return MACRO(T(SPC), T(EQL), D(LSFT), T(DOT), U(LSFT), T(SPC), END);
    case 3: return MACRO(T(SPC), D(LSFT), T(COMM), U(LSFT), T(EQL), T(SPC), END);
    case 4: return MACRO(T(SPC), T(MINS), D(LSFT), T(DOT), U(LSFT), T(SPC), END);
    case 5: return MACRO(T(SPC), T(EQL), T(EQL), T(SPC), END);
    case 6: return MACRO(T(SPC), D(LSFT), T(COMM), U(LSFT), T(SPC), END);
    case 7: return MACRO(T(SPC), D(LSFT), T(DOT), U(LSFT), T(SPC), END);
    case 8: return MACRO(T(SPC), D(LSFT), T(EQL), U(LSFT), T(SPC), END);
    case 9: return MACRO(D(LSFT), T(SCLN), U(LSFT), T(SPC), END);
    case 10: return MACRO(T(BTN1), W(100), T(BTN1), W(100), T(BTN1), END);
    case 11: return MACRO(D(LSFT), W(50), T(BTN1), W(50), U(LSFT), END);
    case 12: return MACRO(D(LCTL), W(50), T(BTN1), W(50), U(LCTL), END);
    case 13: return MACRO(D(LALT), T(TAB), END);
    case 14: return MACRO(D(LGUI), T(TAB), END);
    case 15: return MACRO(D(LCTL), T(TAB), END);
    }
  }
  return MACRO_NONE;
};

/* enum combos { */
/*   SD_ENT, */
/*   KL_ENT, */
/* }; */

/* const uint16_t PROGMEM sd_combo[] = {KC_S, KC_D, COMBO_END}; */
/* const uint16_t PROGMEM kl_combo[] = {KC_K, KC_L, COMBO_END}; */

/* combo_t key_combos[COMBO_COUNT] = { */
/*   [SD_ENT] = COMBO(sd_combo, KC_ENT), */
/*   [KL_ENT] = COMBO(kl_combo, KC_ENT), */
/* }; */

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
  
[_BL] = LAYOUT_PARADEON(
    KC_ESC, LT(_ML, KC_Q), KC_W, KC_E, KC_R, KC_T, KC_Y, KC_U, KC_I, KC_O, KC_P, KC_BSPC,
    OSM(MOD_LCTL), KC_A, KC_S, KC_D, KC_F, KC_G, KC_H, KC_J, KC_K, KC_L, OSL(_RL),
    OSM(MOD_LSFT), KC_Z, KC_X, KC_C, KC_V, KC_B, KC_N, KC_M, KC_COMM, LT(_LL, KC_DOT), OSM(MOD_LALT), 
    OSL(_XL), KC_LEAD, KC_LGUI, OSL(_LL), KC_SPC, KC_ENT, KC_LEFT, KC_DOWN, KC_UP, KC_RIGHT), 

[_LL] = LAYOUT_PARADEON(
    KC_TRNS, M_SWITCH_MAC_START, M_SWITCH_WIN_START, S(KC_INS), LCA(KC_TAB), KC_INS, KC_TRNS, KC_4, KC_5, KC_6, KC_TILD, KC_PIPE,
    KC_TRNS, KC_LALT, TO(_ML), TO(_NL), TO(_VL), TO(_GL), KC_0, KC_1, KC_2, KC_3, KC_TAB,
    KC_TRNS, KC_DEL, KC_ESC, KC_TRNS, KC_TRNS, KC_TRNS, KC_7, KC_8, KC_9, KC_QUES, KC_TRNS,
    KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_HOME, KC_PGDOWN, KC_PGUP, KC_END),

[_RL] = LAYOUT_PARADEON(
    KC_TRNS, KC_QUOT, KC_LBRC, KC_LPRN, KC_LCBR, KC_SLSH, KC_BSLS, KC_CIRC, KC_UNDS, KC_EXLM, KC_NO, KC_NO,
    KC_TRNS, KC_DLR, KC_DQT, KC_ASTR, KC_EQL, KC_MINS, KC_AMPR, KC_COLN, KC_SCLN, MO(_FL), KC_TRNS, 
    KC_TRNS, KC_PERC, KC_RBRC, KC_RPRN, KC_RCBR, KC_PLUS, KC_AT, KC_HASH, KC_GRV, KC_NO, KC_NO,
    KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_HOME, KC_PGDOWN, KC_PGUP, KC_END),

[_NL] = LAYOUT_PARADEON(
    KC_TRNS, KC_QUOT, KC_LBRC, KC_LPRN, KC_LCBR, KC_SLSH, KC_BSLS, KC_4, KC_5, KC_6, KC_TILD, KC_TRNS,
    KC_TRNS, KC_DLR, KC_DQT, KC_ASTR, KC_EQL, KC_MINS, KC_0, KC_1, KC_2, KC_3, TO(_BL),
    OSL(_NAL), KC_PERC, KC_RBRC, KC_RPRN, KC_RCBR, KC_PLUS, KC_7, KC_8, KC_9, KC_DOT, OSL(_NCL),
    KC_TRNS, KC_TRNS, KC_TRNS, OSL(_NSL), KC_TRNS, KC_TRNS, KC_LEFT, KC_DOWN, KC_UP, KC_RIGHT),

[_NSL] = LAYOUT_PARADEON(
    KC_TRNS, KC_QUOT, KC_LBRC, KC_LPRN, KC_LCBR, KC_SLSH, KC_BSLS, KC_CIRC, KC_UNDS, KC_EXLM, KC_TILD, KC_TRNS,
    KC_TRNS, KC_DLR, KC_DQT, KC_ASTR, KC_EQL, KC_MINS, KC_AMPR, KC_COLN, KC_SCLN, KC_NO, KC_PIPE,
    KC_TRNS, KC_PERC, KC_RBRC, KC_RPRN, KC_RCBR, KC_PLUS, KC_AT, KC_HASH, KC_COMM, KC_QUES, KC_TRNS,
    KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS),

[_NAL] = LAYOUT_PARADEON(
    KC_TRNS, KC_Q, KC_W, KC_E, KC_R, KC_T, KC_Y, KC_U, KC_I, KC_O, KC_P, KC_TRNS,
    KC_TRNS, KC_A, KC_S, KC_D, KC_F, KC_G, KC_H, KC_J, KC_K, KC_L, KC_NO,
    KC_TRNS, KC_Z, KC_X, KC_C, KC_V, KC_B, KC_N, KC_M, KC_LT, KC_GT, KC_TRNS, 
    KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS), 

[_NCL] = LAYOUT_PARADEON(
    KC_TRNS, S(KC_Q), S(KC_W), S(KC_E), S(KC_R), S(KC_T), S(KC_Y), S(KC_U), S(KC_I), S(KC_O), S(KC_P), KC_TRNS,
    KC_TRNS, S(KC_A), S(KC_S), S(KC_D), S(KC_F), S(KC_G), S(KC_H), S(KC_J), S(KC_K), S(KC_L), KC_NO,
    KC_TRNS, S(KC_Z), S(KC_X), S(KC_C), S(KC_V), S(KC_B), S(KC_N), S(KC_M), KC_LT, KC_QUES, KC_TRNS, 
    KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS), 

[_NCL2] = LAYOUT_PARADEON(
    KC_TRNS, S(KC_Q), S(KC_W), S(KC_E), S(KC_R), S(KC_T), S(KC_Y), S(KC_U), S(KC_I), S(KC_O), S(KC_P), KC_TRNS,
    KC_TRNS, S(KC_A), S(KC_S), S(KC_D), S(KC_F), S(KC_G), S(KC_H), S(KC_J), S(KC_K), S(KC_L), TO(_BL),
    KC_TRNS, S(KC_Z), S(KC_X), S(KC_C), S(KC_V), S(KC_B), S(KC_N), S(KC_M), KC_LT, KC_QUES, KC_TRNS, 
    KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS), 

[_FL] = LAYOUT_PARADEON(
    KC_TRNS, KC_F9, KC_F10, KC_F11, KC_F12, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,
    KC_TRNS, KC_F5, KC_F6, KC_F7, KC_F8, KC_NO, KC_NO, KC_LSFT, KC_LCTL, KC_NO, KC_NO,
    KC_TRNS, KC_F1, KC_F2, KC_F3, KC_F4, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,
    KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS),

[_XL] = LAYOUT_PARADEON(
    KC_NO, KC_CALC, KC_MAIL, KC_MYCM, KC_WSCH, KC_RETURN, KC_AGAIN, KC_STOP, KC_CAPS, TO(_NCL2), KC_EXEC, LCA(KC_DEL),
    KC_NO, KC_BRID, KC_BRIU, KC_MSTP, KC_WBAK, KC_SEPARATOR, KC_UNDO, KC_CUT, KC_COPY, KC_PASTE, KC_FIND,
    KC_NO, KC_MPRV, KC_MNXT, KC_MPLY, KC_WFWD, KC_OUT, KC_ALT_ERASE, KC_SYSREQ, KC_CANCEL, LALT(KC_F4), KC_PRIOR,
    KC_TRNS, KC_APP, KC_VOLD, KC_VOLU, KC_MUTE, KC_OPER, KC_CLEAR_AGAIN, KC_CRSEL, KC_EXSEL, KC_NO), 

[_VL] = LAYOUT_PARADEON(
    KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_UP, KC_PGUP, KC_TRNS, KC_TRNS,
    KC_TRNS, KC_LALT, KC_LSFT, KC_LCTL, KC_TRNS, KC_TRNS, KC_HOME, KC_LEFT, KC_RIGHT, KC_END, TO(_BL),
    KC_TRNS, KC_DEL, LCTL(KC_X), LCTL(KC_C), LCTL(KC_V), LSFT(KC_INS), KC_DOWN, KC_PGDOWN, KC_TRNS, KC_TRNS, KC_TRNS,
    KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS),

[_GL] = LAYOUT_PARADEON(
    KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_UP, KC_PGUP, KC_TRNS, KC_TRNS,
    KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_HOME, KC_LEFT, KC_RIGHT, KC_END, TO(_BL),
    KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_DOWN, KC_PGDOWN, KC_TRNS, KC_TRNS, KC_TRNS,
    KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS),

[_ML] = LAYOUT_PARADEON(
    KC_TRNS, KC_TRNS, KC_BTN1, M_DOUBLE_CLICK, M_CTRL_CLICK, M_TRIPLE_CLICK, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,
    TO(_BL), KC_NO, KC_BTN3, KC_BTN2, M_SHIFT_CLICK, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, TO(_BL),
    KC_TRNS, KC_DEL, LCTL(KC_X), LCTL(KC_C), LCTL(KC_V), LSFT(KC_INS), KC_PGDOWN, KC_NO, KC_NO, KC_NO, KC_NO,
    KC_TRNS, KC_TRNS, KC_TRNS, TO(_BL), KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS),

/* [_SL] = LAYOUT_PARADEON( */
/*     KC_NO, M_SWITCH_MAC_START, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_UP, KC_NO, KC_NO, KC_NO, */
/*     KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_LEFT, KC_RIGHT, KC_NO, KC_NO, */
/*     KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_DOWN, KC_NO, KC_NO, KC_UP, KC_NO, */
/*     KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_LEFT, KC_DOWN, KC_RIGHT), */

/* [_CL] = LAYOUT_PARADEON( */
/*     M_SPACE_LT_SPACE, M_SPACE_GT_SPACE, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, */
/*     KC_TRNS, M_SPACE_EQL_SPACE, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, */
/*     M_SPACE_EQL_EQL_SPACE, M_SPACE_LT_EQL_SPACE, M_SPACE_EQL_GT_SPACE, M_SPACE_MIN_GT_SPACE, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, */
/*     KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, M_SPACE_PLUS_SPACE, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS), */

};
