#include "../../config.h"

// #define ONESHOT_TAP_TOGGLE 3
#define ONESHOT_TIMEOUT 2000
#define PERMISSIVE_HOLD
// #define LEADER_TIMEOUT 300
/* #define IGNORE_MOD_TAP_INTERRUPT */

// #define MOUSEKEY_DELAY 200
// #define MOUSEKEY_MAX_SPEED 40
#define MOUSEKEY_WHEEL_MAX_SPEED 8
#define MOUSEKEY_WHEEL_TIME_TO_MAX 40
